---
- hosts: test_group
  become: yes

#  vars_prompt:

#  - name: "new_pwd"
#    prompt: "Enter new password"
#    private: yes
#    encrypt: "md5_crypt"
#    confirm: yes
#    salt_size: 7


  tasks:

  - name: "print"
    debug:
      msg: "{{user_name}}"

#  - name: "Change password"
#    user:
#      name: "{{user_name}}"
#      password: "{{new_pwd}}"
#      update_password: always
