---
- hosts: test_group
  become: false

  tasks:

  - name: "Current date(format: 190101)"
    shell: "date +%y%m%d"
    register: dateValue

  - name: "Set variables"
    set_fact:
      cur_date: "{{dateValue.stdout}}"

  - name: "print"
    debug:
      msg: "extra variables: {{server_dir}}, {{remoteClient_dir}}, cur_date: {{cur_date}}"
  

      #  - name: "Backup old dir"
      #    command: "mv ~/ansible_test/testDir ~/ansible_test/testDir_{{cur_date}}"

  - name: "Send new dir"
    copy:
      src: "{{server_dir}}"
      dest: "{{remoteClient_dir}}"
      mod: 0744    

