---
- hosts: test_group
  gather_facts: no
  become: yes
  become_user: root

  vars_prompt:
  - name: "user_name"
    prompt: "Enter username"
    private: no

  - name: "new_pwd"
    prompt: "Enter new password"
    private: yes
    encrypt: "md5_crypt"
    confirm: yes
    salt_size: 7


  tasks:
  - name: "print"
    debug:
      msg: "{{user_name}}"

  - name: "Change password"
    user:
      name: "{{user_name}}"
      password: "{{new_pwd}}"
      update_password: "always"

## for AWX
#      password: "{{new_pwd | password_hash('sha512')}}"
#      shell: "/bin/bash"
